CREATE table ORD(
  ORDID  	NUMBER(4) NOT NULL,
  ORDERDATE	DATE,
  COMMPLAN	VARCHAR2(1),
  CUSTID	NUMBER(6) NOT NULL,
  SHIPDATE	DATE,
  TOTAL		NUMBER(8,2)
);

CREATE table PRODUCT(
  PRODID	NUMBER(6) NOT NULL,
  DESCRIP	VARCHAR2(30)
);

CREATE table ITEM(
  ORDID		NUMBER(4) NOT NULL,
  ITEMID	NUMBER(4) NOT NULL,
  PRODID	NUMBER(6),
  ACTUALPRICE	NUMBER(8,2),
  QTY		NUMBER(8),
  ITEMTOT	NUMBER(8,2)
);

CREATE table CUSTOMER(
  CUSTID	NUMBER(6) NOT NULL,
  NAME		VARCHAR2(45),
  ADDRESS	VARCHAR2(40),
  CITY		VARCHAR2(30),
  STATE		VARCHAR2(2),
  ZIP		VARCHAR2(9),
  AREA		NUMBER(3),
  PHONE		VARCHAR2(9),
  REPID		NUMBER(4) NOT NULL,
  CREDITLIMIT	NUMBER(9,2),
  COMMENTS	LONG
);

CREATE table PRICE(
  PRODID	NUMBER(6) NOT NULL,
  STDPRICE	NUMBER(8,2),
  MINPRICE	NUMBER(8,2),
  STARTDATE	DATE,
  ENDDATE	DATE
);